steps:
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=manifests/deployment.yaml
  - --location=asia-south1
  - --cluster=mbrw-dev-cluster-4
  dir: 'b'


options:
 logging: CLOUD_LOGGING_ONLY
