apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-login
  template:
    metadata:
      labels:
        app: go-login
    spec:
      containers:
      - name: server
        image: asia-south1-docker.pkg.dev/hbl-poc-digfac-anthos-prj/mb-devops/myimage
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
